site_name: My Site

theme:
  name: material
  palette:
    scheme: slate
  font:
    text: Roboto
  features:
    - navigation.top
    - navigation.sections
    - toc.follow
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - toc.integrate

plugins:
  - search
  - mkdocs-nav-weight:
      section_renamed: true
      index_weight: -100
      warning: true
      reverse: false
      headless_included: false
  - mermaid2:
      arguments:
        theme: dark

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid

extra_css:
  - stylesheets/mermaid.css
