site_name: My Site

theme:
  name: material
  palette:
    scheme: slate

plugins:
  - search
  - mermaid2:
      arguments:
        theme: dark

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid

extra_css:
  - stylesheets/mermaid.css
